minimal_mistakes_skin: "default"
primary_color: "#2C7BE5"
title: 嘉美技術株式会社
logo: /assets/images/logo.png
description: 小微企业数字转型的长期伙伴
locale: zh-CN
subtitle: JIAMEI Technology
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

