minimal_mistakes_skin: "air"
title: 嘉美技術株式会社
logo: /assets/images/logo.png
description: 小微企业数字转型的长期伙伴
locale: zh-CN
subtitle: JIAMEI Technology
remote_theme: "mmistakes/minimal-mistakes"
include_cached: false

plugins:
  - jekyll-include-cache

